### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [hbridges/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by hbridges** [comment]
added the <meta name="viewport" content="width=device-width, initial-scale=1"> 
tag to the header.

**Comment by hbridges** [comment]
meta name="viewport" content="width=device-width, initial-scale=1"

**Comment by MarcoMorawec** [comment]
:+1: @hbridges 

Great solution. 

Make sure you close this issue, now that you have it all solved :)
